version: '3.4'

services:
  gateway:
    image: nginx
    ports:
      - $NGINX_LISTEN:80
    volumes:
      - ./docker/gateway/files/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/gateway/files/conf.d:/etc/nginx/conf.d
      - ./files/public/:/var/www/scrapper/files/public

  scrapper:
    build:
      context: .
      target: scrapper-dev
      dockerfile: docker/scrapper/Dockerfile
    volumes:
      - ./:/var/www/scrapper
    environment:
      XDEBUG_REMOTE_HOST: $XDEBUG_REMOTE_HOST
      XDEBUG_REMOTE_PORT: $XDEBUG_REMOTE_PORT
      XDEBUG_IDEKEY: $XDEBUG_IDEKEY
      SCRAPPER_DEBUG: 1
      SCRAPPER_TEMPORARY_PATH: /tmp
      SCRAPPER_PERSISTENT_PATH: /var/www/scrapper/files/public